# Generated by Django 3.2.9 on 2021-12-02 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('public', models.CharField(choices=[('PR', 'Private'), ('RO', 'Read-Only'), ('PB', 'Public')], default='PR', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.IntegerField()),
                ('public', models.CharField(choices=[('PR', 'Private'), ('RO', 'Read-Only'), ('PB', 'Public')], default='PR', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('start', models.IntegerField()),
                ('public', models.CharField(choices=[('PR', 'Private'), ('RO', 'Read-Only'), ('PB', 'Public')], default='PR', max_length=2)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_rackspace.unit_set+', to='contenttypes.contenttype')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.rack')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='JBOD',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rackspace.unit')),
                ('disk_slots', models.IntegerField()),
                ('hdisk_size', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rackspace.unit',),
        ),
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rackspace.unit')),
                ('ports', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rackspace.unit',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rackspace.unit')),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('hdisk_size', models.FloatField()),
                ('graphics', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rackspace.unit',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rackspace.unit')),
                ('ports', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rackspace.unit',),
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rackspace.unit')),
                ('watt_hours', models.FloatField()),
                ('max_watts', models.FloatField()),
                ('outlets', models.IntegerField()),
                ('surge_protection', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rackspace.unit',),
        ),
        migrations.CreateModel(
            name='NetworkCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('network_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackspace.network')),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.server')),
            ],
        ),
    ]
