# Generated by Django 3.0 on 2021-11-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PR', 'Private'), ('RO', 'Read-Only'), ('PB', 'Public')], default='PR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.IntegerField()),
                ('public', models.ManyToManyField(to='rackspace.Public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('start', models.IntegerField()),
                ('Ports', models.IntegerField()),
                ('public', models.ManyToManyField(to='rackspace.Public')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.Rack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
