# Generated by Django 3.2.9 on 2021-12-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='network',
            name='prefix',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkcard',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='rackspace.network'),
        ),
        migrations.AlterField(
            model_name='networkcard',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='rackspace.server'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rackspace.rack'),
        ),
    ]
