# Generated by Django 3.0.7 on 2021-11-18 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rackspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('public', models.ManyToManyField(to='rackspace.Public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='patchpanel',
            old_name='Ports',
            new_name='ports',
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('start', models.IntegerField()),
                ('watt_hours', models.FloatField()),
                ('max_watts', models.FloatField()),
                ('outlets', models.IntegerField()),
                ('surge_protection', models.BooleanField()),
                ('public', models.ManyToManyField(to='rackspace.Public')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.Rack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('start', models.IntegerField()),
                ('ports', models.IntegerField()),
                ('public', models.ManyToManyField(to='rackspace.Public')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.Rack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('start', models.IntegerField()),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('hdisk_size', models.FloatField()),
                ('graphics', models.FloatField()),
                ('public', models.ManyToManyField(to='rackspace.Public')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.Rack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rackspace.Network')),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.Server')),
            ],
        ),
        migrations.CreateModel(
            name='JBOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('start', models.IntegerField()),
                ('disk_slots', models.IntegerField()),
                ('hdisk_size', models.FloatField()),
                ('public', models.ManyToManyField(to='rackspace.Public')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackspace.Rack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
