# Generated by Django 3.2.9 on 2021-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackspace', '0002_auto_20211118_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkcard',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
