# Generated by Django 3.2.9 on 2021-12-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackspace', '0003_unit_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkcard',
            unique_together={('network_id', 'ip_address')},
        ),
    ]
