# Generated by Django 3.0.7 on 2021-12-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rackspace', '0004_alter_networkcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkcard',
            name='network_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='rackspace.Network'),
        ),
    ]
